language: python

python:
  - 3.9.1

before_install:
  - export DJANGO_SETTINGS_MODULE=py3learn.dev_settings

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py collectstatic --no-input

script:
  - python manage.py test
