# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageDictionnary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationCouple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_word', models.CharField(max_length=200)),
                ('word_to_learn', models.CharField(max_length=200)),
                ('language_dictionnary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.LanguageDictionnary')),
            ],
        ),
    ]
