# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20160517_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_word', models.CharField(max_length=200)),
                ('word_to_learn', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='LanguageDictionnary',
            new_name='Dictionary',
        ),
        migrations.RemoveField(
            model_name='translationcouple',
            name='language_dictionnary',
        ),
        migrations.DeleteModel(
            name='TranslationCouple',
        ),
        migrations.AddField(
            model_name='translation',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Dictionary'),
        ),
    ]
