# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20160520_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['known_word']},
        ),
    ]
