# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_added_word_knowledge_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='importance',
            field=models.CharField(choices=[('MH', 'Must know'), ('SH', 'Should know'), ('NTH', 'Nice to know')], default='MH', max_length=3),
        ),
    ]
