# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_rythmnotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rythmnotation',
            name='successes',
            field=models.BigIntegerField(default=0),
        ),
    ]
