# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20160525_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rythmnotation',
            name='next_repetition',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
